# fly.toml app configuration file generated for g-cal-companion on 2023-10-16T16:57:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "g-cal-companion"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
